# Generated by Django 4.1.1 on 2022-09-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='placa',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
